name: showcase_showcase_flutter
description: "A showcase app for Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # core
  riverpod: ^2.5.1
  go_router: ^14.2.7
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # api
  retrofit: ^4.4.0
  logger: any
  dio: ^5.0.3

  # app
  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.1
  flutter_localization: ^0.2.2
  dartx: ^1.2.0
  flutter_dotenv: ^5.1.0
  collection: ^1.18.0

  # ui related
  flutter_animate: ^4.2.0+1
  cached_network_image: ^3.3.0
  gap: ^3.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.5
  cached_network_image: ^3.2.2
  flutter_svg: ^2.0.4
  lottie: ^3.1.0

flutter:

  fonts:
    - family: Baloo
      fonts:
        - asset: resources/fonts/BalooBhaijaan/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: resources/fonts/BalooBhaijaan/BalooBhaijaan2-SemiBold.ttf
          weight: 600
        - asset: resources/fonts/BalooBhaijaan/BalooBhaijaan2-Bold.ttf
          weight: 700

  assets:
    - .env
    - resources/
    - resources/fonts/
    - resources/strings/
    - resources/images/
    - resources/icons/
    - resources/lotties/

  uses-material-design: true